apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault2
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: test
  source:
    path: .
    repoURL: https://github.com/elimaneg/bv.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true

  ignoreDifferences:
  - group: apps
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec
