apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
- crd.yaml
- vault-operator.yaml
- rbac.yaml
#- cr.yaml
- keycloakrealmimports.k8s.keycloak.org-v1.yaml
- keycloaks.k8s.keycloak.org-v1.yaml
- keycloak-tls.yaml
- keycloak-postgres-creds.yaml
- keycloak-postgres-db.yaml
- keycloak-operator.yaml
